// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd7JQSvR0OvyGvievtYpZ6nsRToDmu07U',
    appId: '1:93821656244:web:8e3aa56d1eb0429ee00be1',
    messagingSenderId: '93821656244',
    projectId: 'smatrackxapp',
    authDomain: 'smatrackxapp.firebaseapp.com',
    storageBucket: 'smatrackxapp.appspot.com',
    measurementId: 'G-S7N6QNZ6ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdrEFiuZccbqDqVcHndteT_RkypJLZCDs',
    appId: '1:93821656244:android:55a94123a6e74a38e00be1',
    messagingSenderId: '93821656244',
    projectId: 'smatrackxapp',
    storageBucket: 'smatrackxapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWGX-lMGu-XEBZujt63HVmVBc7W8LFmbs',
    appId: '1:93821656244:ios:5e6358d77b937733e00be1',
    messagingSenderId: '93821656244',
    projectId: 'smatrackxapp',
    storageBucket: 'smatrackxapp.appspot.com',
    iosBundleId: 'com.alamsyah.smatrackx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWGX-lMGu-XEBZujt63HVmVBc7W8LFmbs',
    appId: '1:93821656244:ios:bc26248f8b602f68e00be1',
    messagingSenderId: '93821656244',
    projectId: 'smatrackxapp',
    storageBucket: 'smatrackxapp.appspot.com',
    iosBundleId: 'com.alamsyah.smatrackx.RunnerTests',
  );
}
